"""add by_default column to users

Revision ID: 923b309f36a8
Revises: 29d9ff120977
Create Date: 2026-03-26 14:58:36.199011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923b309f36a8'
down_revision: Union[str, None] = '29d9ff120977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('by_default', sa.Integer(), nullable=True), schema='taskapi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'by_default', schema='taskapi')
    # ### end Alembic commands ###
